// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
import type { ErrorRequestHandler, RequestHandler } from 'express';
import type { Logger } from 'pino';
import type { ApiErrorBody } from '../../shared/index.ts';
import { AppError } from '../lib/errors.ts';

export const notFoundHandler: RequestHandler = (req, res) => {
  const body: ApiErrorBody = {
    error: { code: 'NOT_FOUND', message: 'No such endpoint', requestId: String(req.id ?? '') },
  };
  res.status(404).json(body);
};

/** Turns every error into the standard envelope. Internal details never leave the server. */
export function errorHandler(logger: Logger): ErrorRequestHandler {
  return (err, req, res, _next) => {
    const requestId = String(req.id ?? '');
    let e: AppError;
    if (err instanceof AppError) {
      e = err;
    } else if (err?.type === 'entity.too.large') {
      e = new AppError(413, 'BAD_REQUEST', 'Request is too large');
    } else if (err?.type === 'entity.parse.failed') {
      e = new AppError(400, 'BAD_REQUEST', 'Malformed JSON');
    } else {
      logger.error({ err, requestId, path: req.path }, 'unhandled error');
      e = new AppError(500, 'INTERNAL', 'Something went wrong. Please try again.');
    }
    if (e.status >= 500 && err instanceof AppError)
      logger.warn({ requestId, code: e.code, cause: (err as { cause?: unknown }).cause }, e.message);
    if (res.headersSent) return;
    const body: ApiErrorBody = {
      error: {
        code: e.code,
        message: e.message,
        requestId,
        ...(e.details !== undefined ? { details: e.details } : {}),
      },
    };
    res.status(e.status).json(body);
  };
}
