// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
import type { Logger } from 'pino';
import type { Env } from './config/env.ts';
import type { RpcGateway } from './supabase/rpc.ts';
import type { AuthGateway } from './supabase/auth.ts';
import type { SessionManager } from './security/session.ts';
import type { Limiters } from './security/rate-limit.ts';
import type { ImageStore } from './modules/images/image-store.ts';
import type { MapContext } from './modules/mappers.ts';

/** Everything a route needs, passed in explicitly (easy to fake in tests). */
export interface Deps {
  env: Env;
  logger: Logger;
  rpc: RpcGateway;
  auth: AuthGateway;
  sessions: SessionManager;
  limiters: Limiters;
  images: ImageStore;
  map: MapContext;
}
