// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/**
 * Authenticated encryption for cookie payloads (AES-256-GCM).
 *
 * Sessions hold the Supabase access/refresh tokens. They live only in HttpOnly cookies and are
 * encrypted, so neither page JavaScript nor anyone reading a cookie jar can use them. The
 * "purpose" string is bound as additional authenticated data: a customer cookie cannot be
 * replayed as a vendor cookie, and an OAuth-state cookie cannot be replayed as a session.
 */
import { Buffer } from 'node:buffer';
import {
  createCipheriv,
  createDecipheriv,
  createHash,
  hkdfSync,
  randomBytes,
  timingSafeEqual,
} from 'node:crypto';

const VERSION = 'v1';
const IV_BYTES = 12;
const TAG_BYTES = 16;

function deriveKey(secret: string): Buffer {
  return Buffer.from(
    hkdfSync('sha256', Buffer.from(secret, 'utf8'), Buffer.alloc(0), 'rozbazaar-cookie-v1', 32),
  );
}

export class Sealer {
  private readonly keys: Buffer[];

  /** The first secret encrypts; every secret is tried for decryption (for key rotation). */
  constructor(secrets: readonly string[]) {
    if (!secrets.length) throw new Error('Sealer needs at least one secret');
    this.keys = secrets.map(deriveKey);
  }

  seal(purpose: string, value: unknown): string {
    const iv = randomBytes(IV_BYTES);
    const cipher = createCipheriv('aes-256-gcm', this.keys[0]!, iv);
    cipher.setAAD(Buffer.from(purpose, 'utf8'));
    const body = Buffer.concat([cipher.update(JSON.stringify(value), 'utf8'), cipher.final()]);
    const tag = cipher.getAuthTag();
    return `${VERSION}.${Buffer.concat([iv, tag, body]).toString('base64url')}`;
  }

  /** Returns null for anything tampered, truncated, expired-key or for another purpose. */
  open<T>(purpose: string, token: string | undefined | null): { value: T; rotated: boolean } | null {
    if (!token || typeof token !== 'string' || !token.startsWith(`${VERSION}.`) || token.length > 8192)
      return null;
    let raw: Buffer;
    try {
      raw = Buffer.from(token.slice(VERSION.length + 1), 'base64url');
    } catch {
      return null;
    }
    if (raw.length < IV_BYTES + TAG_BYTES + 2) return null;
    const iv = raw.subarray(0, IV_BYTES);
    const tag = raw.subarray(IV_BYTES, IV_BYTES + TAG_BYTES);
    const body = raw.subarray(IV_BYTES + TAG_BYTES);
    for (let i = 0; i < this.keys.length; i++) {
      try {
        const d = createDecipheriv('aes-256-gcm', this.keys[i]!, iv);
        d.setAAD(Buffer.from(purpose, 'utf8'));
        d.setAuthTag(tag);
        const json = Buffer.concat([d.update(body), d.final()]).toString('utf8');
        return { value: JSON.parse(json) as T, rotated: i > 0 };
      } catch {
        /* try the next key */
      }
    }
    return null;
  }
}

export function sha256Hex(input: string | Buffer, length = 64): string {
  return createHash('sha256').update(input).digest('hex').slice(0, length);
}

export function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString('base64url');
}

/** PKCE S256 code challenge for a verifier. */
export function pkceChallenge(verifier: string): string {
  return createHash('sha256').update(verifier).digest('base64url');
}

export function safeEqual(a: string, b: string): boolean {
  const x = Buffer.from(a);
  const y = Buffer.from(b);
  return x.length === y.length && timingSafeEqual(x, y);
}

/** Reads `exp` from a JWT without verifying it. Only used to decide when to refresh — Supabase verifies. */
export function jwtExpiry(jwt: string): number | null {
  const part = jwt.split('.')[1];
  if (!part) return null;
  try {
    const payload = JSON.parse(Buffer.from(part, 'base64url').toString('utf8')) as { exp?: unknown };
    return typeof payload.exp === 'number' ? payload.exp : null;
  } catch {
    return null;
  }
}
