// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
import type { Response } from 'express';
import type { ApiSuccess } from '../../shared/index.ts';

export function ok<T>(res: Response, data: T, message?: string | null, status = 200): void {
  const body: ApiSuccess<T> = message ? { data, message } : { data };
  res.status(status).json(body);
}

/** Relative in-app path only — blocks open redirects like "//evil.com" or "https://evil.com". */
export function safeReturnPath(v: unknown, fallback = '/'): string {
  if (typeof v !== 'string' || v.length > 200) return fallback;
  if (!v.startsWith('/') || v.startsWith('//') || v.startsWith('/\\') || /[\r\n]/.test(v)) return fallback;
  return v;
}

/**
 * The app that started a login (from the Referer), when it is one of ours — so a login started on
 * beta.rozbazaar.shop comes back there. Anything else falls back to the configured app URL.
 */
export function startingApp(referer: unknown, allowed: readonly string[], fallback: string): string {
  if (typeof referer !== 'string') return fallback;
  try {
    const origin = new URL(referer).origin;
    return allowed.includes(origin) ? origin : fallback;
  } catch {
    return fallback;
  }
}
