// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/** Enums mirrored 1:1 from the Postgres enums in Supabase. Keep these in sync with the DB. */

export const VENDOR_TYPES = ['vegetable', 'fruit', 'onion_potato'] as const;
export type VendorType = (typeof VENDOR_TYPES)[number];

export const TIME_SLOTS = ['morning', 'afternoon', 'evening'] as const;
export type TimeSlot = (typeof TIME_SLOTS)[number];

/** Slot windows in IST, used for display only — the DB decides what is bookable. */
export const SLOT_HOURS: Record<TimeSlot, { start: number; end: number }> = {
  morning: { start: 7, end: 11 },
  afternoon: { start: 12, end: 16 },
  evening: { start: 17, end: 20 },
};

export const BOOKING_STATUSES = [
  'placed',
  'on_the_way',
  'reached',
  'bill_final',
  'bill_approved',
  'paid',
  'delivered',
  'completed',
  'disputed',
  'missed',
  'pending_review',
  'cancelled',
] as const;
export type BookingStatus = (typeof BOOKING_STATUSES)[number];

/** Statuses the vendor can set directly (the rest follow from bill / payment / OTP actions). */
export const VENDOR_SETTABLE_STATUSES = ['on_the_way', 'reached'] as const;
export type VendorSettableStatus = (typeof VENDOR_SETTABLE_STATUSES)[number];

/** Orders the vendor still has to act on. */
export const ACTIVE_VENDOR_STATUSES: readonly BookingStatus[] = [
  'placed',
  'on_the_way',
  'reached',
  'bill_final',
  'bill_approved',
  'paid',
  'disputed',
];

/** Orders the customer can still cancel. */
export const CUSTOMER_CANCELLABLE: readonly BookingStatus[] = ['placed'];

export const PAY_METHODS = ['cash', 'upi_direct'] as const;
export type PayMethod = (typeof PAY_METHODS)[number];

export const LANGS = ['en', 'hi'] as const;
export type Lang = (typeof LANGS)[number];
