// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/** Small pure helpers used on both sides. */

/** Today's date (or +offset days) in India, as YYYY-MM-DD. The DB clock is UTC; business days are IST. */
export function istDate(offsetDays = 0, now: Date = new Date()): string {
  const d = new Date(now.getTime() + offsetDays * 864e5);
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(d);
}

/** Round money to 2 decimals without float noise. */
export function money(n: number): number {
  return Math.round(n * 100) / 100;
}

/** "₹1,234" (whole rupees) or "₹12.50". */
export function rupees(n: number | null | undefined): string {
  const v = Number(n ?? 0);
  const whole = Number.isInteger(v);
  return '₹' + v.toLocaleString('en-IN', { minimumFractionDigits: whole ? 0 : 2, maximumFractionDigits: 2 });
}
