// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/**
 * API response contracts (camelCase). The API maps database rows into these shapes, so the
 * web apps never depend on column names and the DB can change without breaking them.
 */
import type { BookingStatus, Lang, PayMethod, TimeSlot, VendorType } from './enums.ts';

export interface ApiSuccess<T> {
  data: T;
  message?: string;
}
export interface ApiErrorBody {
  error: { code: ApiErrorCode; message: string; details?: unknown; requestId?: string };
}
export type ApiErrorCode =
  | 'BAD_REQUEST'
  | 'VALIDATION'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'CSRF'
  | 'BUSINESS_RULE'
  | 'UPSTREAM'
  | 'INTERNAL';

/** Text that exists in both languages; the app picks one. */
export interface Bilingual {
  en: string;
  hi: string;
}

export interface Area {
  name: string;
  lat: number | null;
  lng: number | null;
  radiusKm: number | null;
  served: boolean;
}

export interface AreaMatch {
  area: string | null;
  inRange: boolean;
  served: boolean;
  confident: boolean;
  distanceKm: number | null;
}

export interface Product {
  id: string;
  /** What the vendor typed (often Roman Hindi, e.g. "Tamatar") — still searchable. */
  name: string;
  nameEn: string | null;
  nameHi: string | null;
  unit: string;
  price: number;
  category: VendorType;
  inStock: boolean;
  imageUrl: string | null;
  vendorId: string;
  vendorName: string | null;
  vendorRating: number | null;
  catalogKey: string | null;
  priceUpdatedAt: string | null;
}

export interface TypeSummary {
  type: VendorType;
  vendorCount: number;
  avgRating: number | null;
}

export interface HomeData {
  area: string;
  areas: string[];
  served: boolean;
  types: TypeSummary[];
  products: Product[];
  favourites: string[];
}

export interface SlotStatus {
  slot: TimeSlot;
  starts: string;
  ends: string;
  free: number;
  isPast: boolean;
  hasRoom: boolean;
}

export interface VendorCard {
  id: string;
  name: string;
  type: VendorType | null;
  photoUrl: string | null;
  avgRating: number | null;
  totalRatings: number;
  ordersCompleted: number | null;
  productCount: number | null;
  booked: number | null;
  capacity: number | null;
}

export interface ProductVendorOption {
  vendorId: string;
  vendorName: string;
  productId: string;
  price: number;
  unit: string;
  inStock: boolean;
  avgRating: number | null;
  totalRatings: number;
}

export interface Address {
  id: string;
  label: string | null;
  house: string | null;
  street: string | null;
  landmark: string | null;
  area: string;
  lat: number | null;
  lng: number | null;
  isDefault: boolean;
}

export interface BookingItem {
  id: string;
  productId: string | null;
  name: string;
  unit: string;
  qty: number;
  finalQty: number | null;
  price: number;
  finalPrice: number | null;
  removed: boolean;
  addedAtDoor: boolean;
  imageUrl: string | null;
}

export interface Booking {
  id: string;
  code: string;
  status: BookingStatus;
  type: VendorType;
  date: string;
  slot: TimeSlot;
  area: string;
  addressLine: string;
  addressLabel: string | null;
  landmark: string | null;
  lat: number | null;
  lng: number | null;
  note: string | null;
  vendorId: string | null;
  vendorName: string | null;
  customerName: string | null;
  /** Only sent to the other party of the order. */
  counterpartPhone: string | null;
  estTotal: number;
  finalTotal: number | null;
  payAmount: number | null;
  payMethod: PayMethod | 'online' | null;
  /** Customer only: the 4-digit code they give the vendor at the door. */
  deliveryOtp: string | null;
  ratingStars: number | null;
  cancelReason: string | null;
  disputeReason: string | null;
  mapsUrl: string | null;
  items: BookingItem[];
  createdAt: string;
}

export interface BillLine {
  itemId: string;
  name: string;
  unit: string;
  bookedQty: number;
  finalQty: number;
  bookedPrice: number;
  finalPrice: number;
  delta: number;
  change: 'same' | 'changed' | 'added' | 'removed';
  imageUrl: string | null;
}

export interface BillPreview {
  code: string;
  status: BookingStatus;
  estTotal: number;
  finalTotal: number;
  lines: BillLine[];
}

export interface AppNotification {
  id: string;
  type: string;
  title: Bilingual;
  message: Bilingual;
  isRead: boolean;
  bookingId: string | null;
  url: string | null;
  createdAt: string;
}

export interface LastOrderItem {
  productId: string;
  name: string;
  unit: string;
  qty: number;
  imageUrl: string | null;
}

export interface CustomerProfile {
  id: string;
  name: string | null;
  phone: string | null;
  email: string | null;
  lang: Lang | null;
}

export interface VendorProfile {
  id: string;
  name: string;
  phone: string | null;
  type: VendorType;
  status: string;
  isActive: boolean;
  shopName: string | null;
  vehicle: string | null;
  photoUrl: string | null;
  areas: string[];
  avgRating: number | null;
  totalRatings: number;
  totalOrders: number;
  defaultCapacity: number;
  lang: Lang | null;
}

export interface VendorProduct extends Omit<Product, 'vendorId' | 'vendorName' | 'vendorRating'> {
  reviewStatus: string | null;
  reviewNote: string | null;
  priceIsStale: boolean;
  sortOrder: number;
}

export interface CatalogItem {
  key: string;
  name: string;
  nameEn: string | null;
  nameHi: string | null;
  unit: string | null;
  category: VendorType;
  imageUrl: string | null;
}

export interface VendorSlotDay {
  date: string;
  slot: TimeSlot;
  isOpen: boolean;
  capacity: number;
  booked: number;
}

export interface VendorReview {
  stars: number;
  comment: string | null;
  customerName: string | null;
  createdAt: string;
}

export interface VendorStats {
  sales: number;
  completed: number;
  avgRating: number | null;
  todaySale: number;
  todayOrders: number;
  todayPending: number;
  totalRatings: number;
  stalePrices: number;
  commissionRate: number;
}

export interface VendorDashboard {
  from: string;
  to: string;
  sale: number;
  orders: number;
  avg: number;
  cash: number;
  upi: number;
  other: number;
  commission: number;
  net: number;
  rate: number;
  booked: number;
  cancelled: number;
  missed: number;
  open: number;
  rating: number | null;
  ratings: number;
  monthly: boolean;
  monthSale: number;
  monthCommission: number;
  chart: { date: string; total: number; orders: number }[];
  items: { name: string; unit: string | null; qty: number; amount: number }[];
  list: {
    code: string;
    date: string;
    slot: TimeSlot | null;
    amount: number;
    method: string | null;
    customerName: string | null;
  }[];
}

export interface VendorPasswordStatus {
  hasPassword: boolean;
  request: { status: string; createdAt: string; decidedAt: string | null } | null;
}

export interface CreatedBooking {
  id: string;
  code: string;
  deliveryOtp: string | null;
}

export interface VendorLoginResult {
  vendor: VendorProfile | null;
  /** True when the account exists but has not finished registration (Google-only, no vendor row). */
  needsRegistration: boolean;
}

export interface SessionInfo<U> {
  authenticated: boolean;
  user: U | null;
}
