// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/**
 * RozBazaar API on Supabase Edge Functions:
 *   https://<project>.supabase.co/functions/v1/api/...
 *
 * Supabase provides SUPABASE_URL, SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY. The session secret
 * comes from the SESSION_SECRET function secret if set, else from app_settings.api_session_secret
 * (readable only with the service key). Any other setting can be overridden with a function secret.
 */
import express from 'express';
import { loadEnv } from './api/config/env.ts';
import { buildDeps, createApp } from './api/app.ts';

const vars = Deno.env.toObject();
const SUPABASE_URL = (vars.SUPABASE_URL ?? '').replace(/\/+$/, '');

async function setting(key: string): Promise<string | undefined> {
  const service = vars.SUPABASE_SERVICE_ROLE_KEY;
  if (!SUPABASE_URL || !service) return undefined;
  const r = await fetch(`${SUPABASE_URL}/rest/v1/app_settings?key=eq.${key}&select=value`, {
    headers: { apikey: service, Authorization: `Bearer ${service}` },
  });
  if (!r.ok) return undefined;
  const rows = (await r.json()) as Array<{ value?: unknown }>;
  const v = rows[0]?.value;
  return typeof v === 'string' ? v : undefined;
}

const env = loadEnv({
  NODE_ENV: 'production',
  LOG_TO_CONSOLE: 'true',
  SESSION_TRANSPORT: 'header',
  TRUST_PROXY: '0',
  // Checked on the live project: Cloudflare sets this to the caller's real IP and refuses requests
  // that try to forge it; X-Forwarded-For only shows Supabase's own proxies.
  CLIENT_IP_HEADER: 'cf-connecting-ip',
  PUBLIC_API_URL: `${SUPABASE_URL}/functions/v1/api`,
  CUSTOMER_APP_URL: 'https://rozbazaar.shop',
  VENDOR_APP_URL: 'https://vendor.rozbazaar.shop',
  CORS_ORIGINS: [
    'https://rozbazaar.shop',
    'https://www.rozbazaar.shop',
    'https://vendor.rozbazaar.shop',
    'https://beta.rozbazaar.shop',
    'https://vendor-beta.rozbazaar.shop',
  ].join(','),
  ...vars,
  SESSION_SECRET: vars.SESSION_SECRET ?? (await setting('api_session_secret')),
});

const app = createApp(buildDeps(env));
// Supabase passes the path with the function name in front (/api/v1/...).
const server = express();
server.disable('x-powered-by');
server.use('/api', app);
server.use(app);
server.listen(Number(vars.PORT ?? 8000));
