// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
import type { ActiveSession } from '../security/session.ts';

declare global {
  namespace Express {
    interface Request {
      /** Set by requireSession / optionalSession. */
      auth?: ActiveSession;
    }
  }
}

export {};
