// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/**
 * Server-side sessions: an encrypted token that only this API can open.
 *
 * Two ways to carry it (SESSION_TRANSPORT):
 * - `cookie` (API on a rozbazaar.shop sub-domain): HttpOnly cookie, described below.
 * - `header` (API on Supabase Edge Functions, a different site): browsers block cross-site
 *   cookies (Safari always), so the same sealed token travels in the `X-RB-Session` header.
 *   The API sends a new value in that response header whenever it changes (login, refresh) and
 *   `cleared` on logout; the app stores it and sends it back. Still opaque and encrypted — the
 *   Supabase tokens inside are never readable by the browser.
 *
 * - One cookie per app ("audience"): a customer session can never act on vendor routes.
 * - `__Host-` prefix in production: Secure, host-only, Path=/ — cannot be set by a subdomain.
 * - SameSite=Lax: not sent on cross-site sub-requests (CSRF), still sent on the OAuth redirect.
 * - The Supabase access token is refreshed here, shortly before it expires, and the cookie is
 *   rewritten; the browser never sees either token.
 */
import type { Request, Response, CookieOptions } from 'express';
import type { Logger } from 'pino';
import type { AuthGateway, AuthSession } from '../supabase/auth.ts';
import { jwtExpiry, type Sealer } from '../lib/crypto.ts';

export type Audience = 'customer' | 'vendor';

interface SessionPayload {
  v: 1;
  aud: Audience;
  at: string;
  rt: string;
  exp: number;
  uid: string;
  /** When this login happened (epoch s) — used for the absolute lifetime. */
  iat: number;
}

export interface ActiveSession {
  audience: Audience;
  userId: string;
  accessToken: string;
}

export interface OAuthState {
  v: 1;
  aud: Audience;
  verifier: string;
  returnTo: string;
  /** Which app (origin) started the login, so beta sites come back to themselves. */
  app?: string;
  iat: number;
}

export type SessionTransport = 'cookie' | 'header';
export const SESSION_HEADER = 'X-RB-Session';
export const SESSION_CLEARED = 'cleared';

const REFRESH_BEFORE_S = 120;

/** Node timers can be unref'd; Deno's (Supabase Edge) are plain numbers. */
function unref(t: unknown): void {
  (t as { unref?: () => void })?.unref?.();
}
const OAUTH_TTL_S = 600;

export class SessionManager {
  private readonly inflight = new Map<string, Promise<AuthSession>>();

  constructor(
    private readonly sealer: Sealer,
    private readonly auth: AuthGateway,
    private readonly opts: {
      secure: boolean;
      /** Cookie lifetime; also the absolute limit before a fresh login is required. */
      maxAgeDays: Record<Audience, number>;
      logger: Logger;
      transport?: SessionTransport;
    },
  ) {}

  cookieName(aud: Audience): string {
    return `${this.opts.secure ? '__Host-' : ''}${aud === 'customer' ? 'rb_c' : 'rb_v'}`;
  }

  private oauthCookieName(): string {
    return `${this.opts.secure ? '__Host-' : ''}rb_oauth`;
  }

  get transport(): SessionTransport {
    return this.opts.transport ?? 'cookie';
  }

  private readRaw(req: Request, aud: Audience): string | undefined {
    if (this.transport === 'header') {
      const h = req.get(SESSION_HEADER);
      return h && h !== SESSION_CLEARED ? h : undefined;
    }
    return req.cookies?.[this.cookieName(aud)] as string | undefined;
  }

  private send(res: Response, aud: Audience, token: string, maxAgeMs: number): void {
    if (this.transport === 'header') res.setHeader(SESSION_HEADER, token);
    else res.cookie(this.cookieName(aud), token, this.cookieOptions(maxAgeMs));
  }

  /**
   * Where to send the browser after a Google login. In header mode the new session rides along in
   * the URL fragment (`#rbs=`), which browsers never send to any server; the app stores it and
   * removes it from the address bar straight away.
   */
  afterLogin(url: string, token: string): string {
    return this.transport === 'header' ? `${url}#rbs=${token}` : url;
  }

  private cookieOptions(maxAgeMs: number): CookieOptions {
    return { httpOnly: true, secure: this.opts.secure, sameSite: 'lax', path: '/', maxAge: maxAgeMs };
  }

  /** Stores the session and returns the sealed token. */
  write(res: Response, aud: Audience, s: AuthSession, loginAt = Math.floor(Date.now() / 1000)): string {
    const payload: SessionPayload = {
      v: 1,
      aud,
      at: s.accessToken,
      rt: s.refreshToken,
      exp: jwtExpiry(s.accessToken) ?? s.expiresAt,
      uid: s.userId,
      iat: loginAt,
    };
    const remainingMs = Math.max(60_000, loginAt * 1000 + this.opts.maxAgeDays[aud] * 864e5 - Date.now());
    const token = this.sealer.seal(`session:${aud}`, payload);
    this.send(res, aud, token, remainingMs);
    return token;
  }

  clear(res: Response, aud: Audience): void {
    if (this.transport === 'header') {
      res.setHeader(SESSION_HEADER, SESSION_CLEARED);
      return;
    }
    res.clearCookie(this.cookieName(aud), {
      httpOnly: true,
      secure: this.opts.secure,
      sameSite: 'lax',
      path: '/',
    });
  }

  /** The raw access token for logout, without refreshing. */
  peekAccessToken(req: Request, aud: Audience): string | null {
    const opened = this.sealer.open<SessionPayload>(`session:${aud}`, this.readRaw(req, aud));
    return opened?.value.at ?? null;
  }

  /**
   * Returns the active session (refreshing it if needed) or null when there is none / it is dead.
   * A dead cookie is cleared so the browser stops sending it.
   */
  async resolve(req: Request, res: Response, aud: Audience): Promise<ActiveSession | null> {
    const raw = this.readRaw(req, aud);
    if (!raw) return null;
    const opened = this.sealer.open<SessionPayload>(`session:${aud}`, raw);
    const p = opened?.value;
    const now = Math.floor(Date.now() / 1000);
    if (!p || p.v !== 1 || p.aud !== aud || now - p.iat > this.opts.maxAgeDays[aud] * 86_400) {
      this.clear(res, aud);
      return null;
    }
    if (p.exp - now > REFRESH_BEFORE_S) {
      if (opened.rotated) this.rewrite(res, aud, p);
      return { audience: aud, userId: p.uid, accessToken: p.at };
    }
    try {
      const fresh = await this.refreshOnce(p.rt);
      if (fresh.userId !== p.uid) throw new Error('refresh returned a different user');
      this.write(res, aud, fresh, p.iat);
      return { audience: aud, userId: fresh.userId, accessToken: fresh.accessToken };
    } catch (err) {
      this.opts.logger.info({ aud, err: (err as Error).message }, 'session refresh failed — signing out');
      this.clear(res, aud);
      return null;
    }
  }

  /** Concurrent requests that all need a refresh share one call (refresh tokens are single-use). */
  private refreshOnce(refreshToken: string): Promise<AuthSession> {
    let p = this.inflight.get(refreshToken);
    if (!p) {
      p = this.auth.refresh(refreshToken).finally(() => {
        unref(setTimeout(() => this.inflight.delete(refreshToken), 5_000));
      });
      this.inflight.set(refreshToken, p);
    }
    return p;
  }

  private rewrite(res: Response, aud: Audience, p: SessionPayload): void {
    const remainingMs = Math.max(60_000, p.iat * 1000 + this.opts.maxAgeDays[aud] * 864e5 - Date.now());
    this.send(res, aud, this.sealer.seal(`session:${aud}`, p), remainingMs);
  }

  /* ---------- OAuth (PKCE) state, bound to this browser ---------- */

  writeOAuthState(res: Response, state: Omit<OAuthState, 'v' | 'iat'>): void {
    const value: OAuthState = { ...state, v: 1, iat: Math.floor(Date.now() / 1000) };
    res.cookie(
      this.oauthCookieName(),
      this.sealer.seal('oauth', value),
      this.cookieOptions(OAUTH_TTL_S * 1000),
    );
  }

  takeOAuthState(req: Request, res: Response): OAuthState | null {
    const opened = this.sealer.open<OAuthState>('oauth', req.cookies?.[this.oauthCookieName()]);
    res.clearCookie(this.oauthCookieName(), {
      httpOnly: true,
      secure: this.opts.secure,
      sameSite: 'lax',
      path: '/',
    });
    const s = opened?.value;
    if (!s || s.v !== 1 || Math.floor(Date.now() / 1000) - s.iat > OAUTH_TTL_S) return null;
    return s;
  }
}
