// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.
/**
 * Minimal Supabase Auth (GoTrue) client. Only the grants this API needs; the browser never talks
 * to Supabase Auth directly any more, so tokens never touch page JavaScript.
 */
import { AppError, unauthenticated, upstream } from '../lib/errors.ts';
import { fetchJson } from './http.ts';

export interface AuthSession {
  accessToken: string;
  refreshToken: string;
  /** Epoch seconds. */
  expiresAt: number;
  userId: string;
  email: string | null;
  isAnonymous: boolean;
  userMeta: Record<string, unknown>;
}

interface GoTrueSession {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  expires_at?: number;
  user?: {
    id: string;
    email?: string | null;
    is_anonymous?: boolean;
    user_metadata?: Record<string, unknown>;
  };
  error?: string;
  error_description?: string;
  msg?: string;
  error_code?: string;
  code?: number | string;
}

export interface AuthGateway {
  signUpAnonymous(): Promise<AuthSession>;
  signInWithPassword(email: string, password: string): Promise<AuthSession>;
  refresh(refreshToken: string): Promise<AuthSession>;
  exchangePkce(authCode: string, codeVerifier: string): Promise<AuthSession>;
  logout(accessToken: string): Promise<void>;
  authorizeUrl(provider: 'google', redirectTo: string, codeChallenge: string): string;
}

export function createAuthGateway(opts: { url: string; anonKey: string; timeoutMs: number }): AuthGateway {
  const base = `${opts.url}/auth/v1`;
  const headers = { apikey: opts.anonKey, 'Content-Type': 'application/json', Accept: 'application/json' };

  async function grant(path: string, body: unknown, badCredsMessage: string): Promise<AuthSession> {
    const { status, body: b } = await fetchJson<GoTrueSession>(`${base}${path}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
      timeoutMs: opts.timeoutMs,
    });
    if (status === 429)
      throw new AppError(429, 'RATE_LIMITED', 'Too many attempts. Please wait a few minutes.');
    if (status >= 500) throw upstream();
    if (status >= 400 || !b?.access_token || !b.refresh_token || !b.user?.id)
      throw unauthenticated(badCredsMessage);
    const expiresAt = b.expires_at ?? Math.floor(Date.now() / 1000) + (b.expires_in ?? 3600);
    return {
      accessToken: b.access_token,
      refreshToken: b.refresh_token,
      expiresAt,
      userId: b.user.id,
      email: b.user.email ?? null,
      isAnonymous: Boolean(b.user.is_anonymous),
      userMeta: b.user.user_metadata ?? {},
    };
  }

  return {
    signUpAnonymous: () => grant('/signup', { data: {} }, 'Could not start a session'),
    signInWithPassword: (email, password) =>
      grant('/token?grant_type=password', { email, password }, 'Wrong phone number or password'),
    refresh: (refreshToken) =>
      grant('/token?grant_type=refresh_token', { refresh_token: refreshToken }, 'Your session has ended'),
    exchangePkce: (authCode, codeVerifier) =>
      grant(
        '/token?grant_type=pkce',
        { auth_code: authCode, code_verifier: codeVerifier },
        'Google sign-in failed. Please try again.',
      ),
    async logout(accessToken) {
      // Best effort: the cookie is cleared regardless.
      await fetchJson(`${base}/logout?scope=local`, {
        method: 'POST',
        headers: { ...headers, Authorization: `Bearer ${accessToken}` },
        timeoutMs: opts.timeoutMs,
      }).catch(() => undefined);
    },
    authorizeUrl(provider, redirectTo, codeChallenge) {
      const q = new URLSearchParams({
        provider,
        redirect_to: redirectTo,
        code_challenge: codeChallenge,
        code_challenge_method: 's256',
      });
      return `${base}/authorize?${q.toString()}`;
    },
  };
}
