/**
 * Builds the API as a Supabase Edge Function: ../supabase/functions/api/
 *
 * The same Express app (apps/api) runs there on Deno. This script copies its sources and the
 * shared package, rewrites the imports for Deno (".js" → ".ts", "@rozbazaar/shared" → relative,
 * npm packages → pinned "npm:" specifiers in deno.json) and writes the entry point.
 *
 *   npm run build:edge      then deploy:  supabase functions deploy api --no-verify-jwt
 *
 * It also writes bundle.js: the same function as ONE plain JavaScript file (npm packages stay
 * imports, resolved by deno.json). Because the repo is public, the deployed function can simply be
 *   import "https://cdn.jsdelivr.net/gh/Vedanshurathi/roz@<commit>/supabase/functions/api/bundle.js";
 * so what runs on Supabase is exactly what is in git at that commit (see docs/DEPLOY.md).
 *
 * Never edit the generated folder by hand — change apps/api and run this again.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = fileURLToPath(new URL('..', import.meta.url));
const out = join(root, '..', 'supabase', 'functions', 'api');
/** The version the API actually uses (its own node_modules first, then the workspace root). */
function installed(pkg) {
  for (const dir of ['apps/api/node_modules', 'node_modules']) {
    const f = join(root, dir, pkg, 'package.json');
    if (existsSync(f)) return JSON.parse(readFileSync(f, 'utf8')).version;
  }
  throw new Error(`${pkg} is not installed — run npm ci`);
}

const NPM = ['express', 'cookie-parser', 'cors', 'express-rate-limit', 'helmet', 'pino', 'pino-http', 'zod'];
const imports = Object.fromEntries(NPM.map((p) => [p, `npm:${p}@${installed(p)}`]));

function walk(dir, skip = () => false) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    if (skip(p)) return [];
    return statSync(p).isDirectory() ? walk(p, skip) : p.endsWith('.ts') ? [p] : [];
  });
}

const sources = [
  ...walk(join(root, 'apps/api/src'), (p) => p.includes(`${'/src/'}dev`) || p.endsWith('/server.ts')).map(
    (f) => ({
      from: f,
      to: join(out, 'api', relative(join(root, 'apps/api/src'), f)),
    }),
  ),
  ...walk(join(root, 'packages/shared/src'), (p) => p.endsWith('.test.ts')).map((f) => ({
    from: f,
    to: join(out, 'shared', relative(join(root, 'packages/shared/src'), f)),
  })),
];

rmSync(out, { recursive: true, force: true });
const HEADER = '// Generated by platform/scripts/build-edge.mjs from platform/ — do not edit here.\n';
for (const { from, to } of sources) {
  let code = readFileSync(from, 'utf8');
  // relative imports: "./x.js" → "./x.ts"
  code = code.replace(/(from\s+|import\s*\(\s*|import\s+)(['"])(\.{1,2}\/[^'"]+?)\.js\2/g, '$1$2$3.ts$2');
  // the shared package → its copied sources
  const shared = relative(dirname(to), join(out, 'shared', 'index.ts'));
  code = code.replace(
    /(['"])@rozbazaar\/shared\1/g,
    `$1${shared.startsWith('.') ? shared : './' + shared}$1`,
  );
  mkdirSync(dirname(to), { recursive: true });
  writeFileSync(to, HEADER + code);
}

writeFileSync(join(out, 'deno.json'), JSON.stringify({ imports }, null, 2) + '\n');
writeFileSync(
  join(out, 'index.ts'),
  `${HEADER}/**
 * RozBazaar API on Supabase Edge Functions:
 *   https://<project>.supabase.co/functions/v1/api/...
 *
 * Supabase provides SUPABASE_URL, SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY. The session secret
 * comes from the SESSION_SECRET function secret if set, else from app_settings.api_session_secret
 * (readable only with the service key). Any other setting can be overridden with a function secret.
 */
import express from 'express';
import { loadEnv } from './api/config/env.ts';
import { buildDeps, createApp } from './api/app.ts';

const vars = Deno.env.toObject();
const SUPABASE_URL = (vars.SUPABASE_URL ?? '').replace(/\\/+$/, '');

async function setting(key: string): Promise<string | undefined> {
  const service = vars.SUPABASE_SERVICE_ROLE_KEY;
  if (!SUPABASE_URL || !service) return undefined;
  const r = await fetch(\`\${SUPABASE_URL}/rest/v1/app_settings?key=eq.\${key}&select=value\`, {
    headers: { apikey: service, Authorization: \`Bearer \${service}\` },
  });
  if (!r.ok) return undefined;
  const rows = (await r.json()) as Array<{ value?: unknown }>;
  const v = rows[0]?.value;
  return typeof v === 'string' ? v : undefined;
}

const env = loadEnv({
  NODE_ENV: 'production',
  LOG_TO_CONSOLE: 'true',
  SESSION_TRANSPORT: 'header',
  TRUST_PROXY: '0',
  // Checked on the live project: Cloudflare sets this to the caller's real IP and refuses requests
  // that try to forge it; X-Forwarded-For only shows Supabase's own proxies.
  CLIENT_IP_HEADER: 'cf-connecting-ip',
  PUBLIC_API_URL: \`\${SUPABASE_URL}/functions/v1/api\`,
  CUSTOMER_APP_URL: 'https://rozbazaar.shop',
  VENDOR_APP_URL: 'https://vendor.rozbazaar.shop',
  CORS_ORIGINS: [
    'https://rozbazaar.shop',
    'https://www.rozbazaar.shop',
    'https://vendor.rozbazaar.shop',
    'https://beta.rozbazaar.shop',
    'https://vendor-beta.rozbazaar.shop',
  ].join(','),
  ...vars,
  SESSION_SECRET: vars.SESSION_SECRET ?? (await setting('api_session_secret')),
});

const app = createApp(buildDeps(env));
// Supabase passes the path with the function name in front (/api/v1/...).
const server = express();
server.disable('x-powered-by');
server.use('/api', app);
server.use(app);
server.listen(Number(vars.PORT ?? 8000));
`,
);

await build({
  entryPoints: [join(out, 'index.ts')],
  outfile: join(out, 'bundle.js'),
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  legalComments: 'none',
  external: [...NPM, 'node:*'],
  banner: { js: HEADER.trim() },
  logLevel: 'warning',
});

const files = walk(out).length + 2;
console.log(`Edge function written to ${relative(process.cwd(), out)} (${files} files)`);
